Add a test case for bats
mocsarcade/enchiridion pull request #40
Opened 2016-10-03 01:27 UTC by Willamin

2016-10-03 01:29 UTC, ehgoodenough approved these changes

2016-10-03 01:29 UTC, ehgoodenough commented on source/scripts/tests/BatTest.js
> +    // Had to use JSON.stringify to compare objects
Hmm.. We should find a better way of comparing two positions, so we don't have to stringify them again next time.

2016-10-03 15:43 UTC, Willamin commented on source/scripts/tests/BatTest.js
> +    // Had to use JSON.stringify to compare objects
I wasn't a huge fan either. An alternative I thought about was making a helper function that takes two positions and checks whether `position1.x == position2.x && position1.y == position2.y`. I wasn't sure where would be best to put a helper function like that

2016-10-08 18:26 UTC, jcpirtle reviewed
Will, change your stringify to what I have in my test and you should be good to go

2016-10-09 17:58 UTC, ehgoodenough requested changes
When we slack-chat'd last Tuesday, we decided to move towards `.eql` instead of `Json.stringify`.

2016-10-09 17:58 UTC, ehgoodenough commented
Also, could you please provide a test link? We've been slacking off on providing those.

2016-10-09 19:12 UTC, Willamin commented
Build link (`production`): https://Willamin.github.io/enchiridion/bat-test
Build link (`development`): https://willamin.github.io/enchiridion/bat-test-dev/

2016-10-09 19:16 UTC, ehgoodenough approved these changes
LGTM! :D

2016-10-09 19:16 UTC, merged